# Generated by Django 4.1.6 on 2023-02-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('desc1', models.TextField(blank=True)),
                ('img1', models.ImageField(upload_to='photos')),
                ('desc2', models.TextField(blank=True)),
                ('img2', models.ImageField(upload_to='photos')),
                ('population', models.BigIntegerField()),
                ('cities', models.IntegerField()),
                ('space', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('image', models.ImageField(upload_to='photos')),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='travel_blog.country')),
            ],
            options={
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='DestinationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_detail', to='travel_blog.destination')),
            ],
        ),
    ]
