# Generated by Django 4.1.6 on 2023-02-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name_plural': 'destinations'},
        ),
    ]
